spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 9000